version: '3.9'

services:
  webapi.db:
    container_name: webapi.db
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - webapi_database_volume:/var/opt/mssql
    environment:
      SA_PASSWORD: "Esed2003@"
      ACCEPT_EULA: "Y"
  webapi:
    container_name: webapi
    depends_on:
     - webapi.db
    environment:
      - DB_CONNECT=Data Source=webapi.db;Initial Catalog=Project6;User ID=sa;Password=Esed2003@;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


